>>>>>> Start pipeline for DBP15K (FR-EN).
>>>>>> Step 1: generate entity sequence.
Traceback (most recent call last):
  File "generate_seq.py", line 19, in <module>
    main(config)
  File "generate_seq.py", line 12, in main
    e2s = Entity2Sequence(config)
  File "/public/home/chenxuan/aligncraft/aligncraft/models/retrievalea/entity2sequence.py", line 15, in __init__
    self.model = self.load_vllm_model(config['vllm']['llms_model_path'], **config)
  File "/public/home/chenxuan/aligncraft/aligncraft/models/retrievalea/entity2sequence.py", line 22, in load_vllm_model
    llm = LLM(model=model_name_or_path, tensor_parallel_size=tensor_parallel_size, swap_space=swap_space)
  File "/public/home/chenxuan/.local/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/public/home/chenxuan/.local/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 570, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/public/home/chenxuan/.local/lib/python3.8/site-packages/vllm/engine/arg_utils.py", line 902, in create_engine_config
    device_config = DeviceConfig(device=self.device)
  File "/public/home/chenxuan/.local/lib/python3.8/site-packages/vllm/config.py", line 1091, in __init__
    raise RuntimeError("Failed to infer device type")
RuntimeError: Failed to infer device type
